import type { Metadata } from "next";
import Link from "next/link";
export const metadata:Metadata={
 title:"Privacy Notice | Precious Afolabi",
 description:"How project enquiry information is used and processed on PreciousWrks.",
 alternates:{canonical:"/privacy"},
 robots:{index:true,follow:true}
};
export default function PrivacyPage(){return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header shell"><Link className="brand" href="/">Precious Afolabi<span>.</span></Link><Link className="header-contact" href="/#contact">Get in touch</Link></header><main id="main" className="service-page shell"><nav className="breadcrumbs"><Link href="/">Home</Link><span>/</span><span>Privacy notice</span></nav><section className="service-hero"><p className="eyebrow">YOUR INFORMATION</p><h1>Privacy notice<span>.</span></h1><p>How I use details shared through this website.</p></section><div className="privacy-copy"><h2>Who handles your enquiry</h2><p>Precious Afolabi, a freelance Nordic localization specialist. Contact <a href="mailto:afolabiprecious233@gmail.com">afolabiprecious233@gmail.com</a> with privacy questions.</p><h2>Information you provide</h2><p>When you submit a project enquiry, the form collects your name, work email, language pair, selected service, deadline, approximate scope and message. Avoid sharing sensitive personal information through this form.</p><h2>Why it is used</h2><p>I use your submitted information to evaluate your request, respond, prepare a quotation and communicate about possible work. This is based on taking steps at your request before a contract and, where applicable, my legitimate interest in responding to business enquiries.</p><h2>Form processing</h2><p>The website form uses Formspree to process submissions and forward enquiries to my email inbox. Their service processes submitted details for delivery. For file sharing and other correspondence, you can contact me directly by email.</p><h2>Retention and your rights</h2><p>Enquiry details are kept only as long as reasonably needed for the enquiry, any resulting business relationship, and applicable record keeping obligations. Contact me to ask about access, correction, deletion or other applicable data rights.</p><h2>Other sites</h2><p>Links to third party websites, including LinkedIn and ProZ, are governed by their own privacy notices.</p></div></main><footer className="footer shell"><p><strong>Precious Afolabi.</strong><span>Nordic localization specialist</span></p><Link href="/">Home</Link></footer></>}
