"use client";
import LuxuryFooter from "@/app/luxury-footer";

import { useState, useEffect, useRef, type FormEvent } from "react";

import { serviceCatalog } from "@/lib/services";

const formspreeEndpoint = "https://formspree.io/f/xljgbnbd";
const email = "afolabiprecious233@gmail.com";
const partners = [
  ["Translated", "/logos/translated.svg", "https://translated.com"],
  ["Protranslate", "/logos/protranslate.png", "https://www.protranslate.net/en/"],
  ["Words in Translation", "/logos/words-in-translation.png", "https://www.wordsintranslation.com/"],
  ["TAYA", "/logos/taya.webp", "https://tayalang.com/en-us/about"],
  ["Future Trans", "/logos/future-trans.png", "https://future-trans.com/"],
  ["GEL Global", "/logos/gel-global.jpg", "https://www.gel-global.com/"],
];
const services = serviceCatalog.map(s => [s.title, s.summary, s.slug]);
const work = [
  {
    image: "/images/case-technical.svg", category: "Technical documentation", pair: "English → Norwegian", service: "MTPE & terminology review",
    title: "Precision in an electric equipment manual",
    challenge: "An operating and maintenance manual needed consistent Norwegian for electrical components, fluids and safety instructions. Refrigerant and coolant had to remain distinct.",
    approach: "I checked the post edited text against the source, aligned component terminology and reviewed warnings, numbers, units and instruction strength.",
    delivery: "Norwegian operating and maintenance content with terminology and safety language reviewed against the English source.",
  },
  {
    image: "/images/case-medical.svg", category: "Medical device documentation", pair: "English → Danish", service: "Translation & revision",
    title: "Consistency across medical document versions",
    challenge: "Updated device documentation needed to follow approved references while preserving warnings, product identifiers and interface references.",
    approach: "I used the approved versions as reference, checked Danish regulatory phrasing and maintained product names, identifiers and UI tags as instructed.",
    delivery: "Danish instructions and supporting documentation translated and reviewed against the supplied reference material.",
  },
  {
    image: "/images/case-software.svg", category: "Software interfaces", pair: "English → Norwegian", service: "Linguistic QA",
    title: "Clear language at the point of action",
    challenge: "Short interface strings needed to communicate user actions and permissions clearly, with consistent terminology and intact placeholders.",
    approach: "I reviewed Norwegian strings against their source and interface context, checked terminology across screens and preserved tags and placeholders.",
    delivery: "Reviewed Norwegian interface content with corrections to wording, consistency and contextual clarity.",
  },
];
type FormState = "idle" | "sending" | "sent" | "error";

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const serviceSelect = useRef<HTMLSelectElement>(null);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("service"); if (requested && serviceCatalog.some(s => s.title === requested) && serviceSelect.current) serviceSelect.current.value = requested; }, []);
  const [formState, setFormState] = useState<FormState>("idle");
  const [formError, setFormError] = useState("");
  async function submitEnquiry(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget;
    const data = new FormData(form);
    if (formState === "sending" || data.get("_gotcha")) return;
    data.set("message", `Service: ${data.get("service")}\nApproximate scope: ${data.get("scope") || "To be confirmed"}\n\n${data.get("message")}`);
    setFormError("");
    setFormState("sending");
    try {
      const response = await fetch(formspreeEndpoint, { method: "POST", headers: { Accept: "application/json" }, body: data });
      if (!response.ok) {
        const result = await response.json().catch(() => ({})) as { errors?: { message?: string }[] };
        throw new Error(result.errors?.map(error => error.message).filter(Boolean).join(" ") || "Your enquiry could not be sent. Try again or email me directly.");
      }
      form.reset(); setFormState("sent"); window.dispatchEvent(new Event("preciouswrks:enquiry-sent"));
    } catch (error) { setFormError(error instanceof Error ? error.message : "Your enquiry could not be sent. Try again or email me directly."); setFormState("error"); }
  }
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <div className="opening opening-header"><header className="site-header shell" id="top"><a className="brand" href="#top">Precious Afolabi<span>.</span></a><button className="mobile-menu-button" type="button" aria-expanded={menuOpen} aria-controls="main-navigation" onClick={() => setMenuOpen(!menuOpen)} onKeyDown={event => { if (event.key === "Escape") setMenuOpen(false); }}>{menuOpen ? "Close menu" : "Menu"}</button><nav id="main-navigation" className={menuOpen ? "is-open" : ""} aria-label="Main navigation" onClick={() => setMenuOpen(false)} onKeyDown={event => { if (event.key === "Escape") setMenuOpen(false); }}><a href="#expertise">Expertise</a><a href="#work">Work</a><a href="/about">About</a><a className="header-contact" href="#contact">Request a quote <span aria-hidden="true">↗</span></a></nav></header></div>
    <main id="main"><div className="opening">
      <section className="hero shell" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">INDEPENDENT NORDIC LANGUAGE SPECIALIST</p><h1 id="hero-title">The right words.<br/>The right nuance.<br/><em>Every time.</em></h1><p className="hero-intro">I’m Precious Afolabi. For over nine years, I’ve helped translation agencies and businesses communicate with confidence across Norwegian, Danish and English. You get precise language, sound judgement and a specialist who takes ownership of every detail.</p><div className="hero-links"><a className="primary-link" href="#contact">Discuss your project</a><a className="text-link" href="/about#my-approach">See my approach</a></div><a className="hero-email" href={`mailto:${email}`}>Or email me directly</a></div><aside className="hero-aside"><img className="personal-portrait" src="/images/precious-portrait.webp" alt="Precious Afolabi, freelance Nordic localization specialist" width="900" height="900" fetchPriority="high" decoding="async" sizes="(max-width: 900px) 86vw, 460px"/></aside></section><div className="proof-strip shell"><span>ONE SPECIALIST, START TO FINISH</span><span>ENGLISH ↔ NORWEGIAN ↔ DANISH</span><span>DETAILS NEVER OVERLOOKED</span></div></div>
      <section className="collaborators shell" aria-labelledby="collaborators-title"><div className="collaborator-heading"><h2 id="collaborators-title">Built on professional collaboration</h2><p>Selected language industry partners</p></div><div className="logo-grid">{partners.map(([name, logo, url]) => <a key={name} className={name === "Future Trans" ? "partner-future" : undefined} href={url} target="_blank" rel="noopener noreferrer" aria-label={`${name} website`} title={name}><img src={logo} alt={`${name} logo`} loading="lazy" decoding="async"/></a>)}</div></section>
      <section id="language-landing" className="language-landing shell" aria-labelledby="language-landing-title"><div><p className="eyebrow">LANGUAGE PAIRS</p><h2 id="language-landing-title">Your words, at home in every language.</h2><p>Six translation directions. One consistent standard of care.</p></div><div className="language-landing-links"><a href="/languages/english-to-norwegian">English ↔ Norwegian <span aria-hidden="true">↗</span></a><a href="/languages/english-to-danish">English ↔ Danish <span aria-hidden="true">↗</span></a><a href="/languages/norwegian-to-danish">Norwegian ↔ Danish <span aria-hidden="true">↗</span></a></div></section><section id="expertise" className="section shell expertise"><div className="section-head"><p className="eyebrow">WHAT I DO</p><h2>Language that works.<br/><em>Not just reads well.</em></h2><p>Accuracy is the starting point. The real craft is making every sentence work for its readers, its purpose and the place it appears.</p></div><div className="service-list">{services.map(([title, detail, slug], index) => <article className="service" key={title}><span className="service-number">0{index + 1}</span><h3><a href={`/services/${slug}`}>{title}</a></h3><div><p>{detail}</p><a className="service-link" href={`/services/${slug}`}>Explore {title.toLowerCase()}</a></div></article>)}</div><p className="language-line"><strong>Working pairs</strong><span>Norwegian ↔ English</span><span>Danish ↔ English</span><span>Norwegian ↔ Danish</span></p></section>
      <section id="work" className="work-section"><div className="shell work-wrap"><div className="work-intro"><p className="eyebrow">SELECTED WORK</p><h2>Precision lives<br/><em>in the details.</em></h2><p>Real examples of the decisions behind accurate, usable language. Project details are anonymized to respect confidentiality.</p></div><div className="work-list">{work.map(({image, category, pair, service, title, challenge, approach, delivery}) => <article className="work-item" key={title}><img className="work-visual" src={image} alt="" loading="lazy" width="920" height="520"/><span>{category}</span><h3>{title}</h3><div className="case-meta"><span>{pair}</span><span>{service}</span></div><dl className="case-details"><div><dt>The challenge</dt><dd>{challenge}</dd></div><div><dt>My work</dt><dd>{approach}</dd></div><div><dt>The deliverable</dt><dd>{delivery}</dd></div></dl></article>)}</div></div></section>
      <section id="about" className="section shell about"><div><p className="eyebrow">ABOUT ME</p><h2>One specialist.<br/><em>Full accountability.</em></h2></div><div className="about-copy"><p className="about-lead">I work where language, context and responsibility meet. Based in London and working with clients worldwide, I bring more than nine years of professional translation and localization experience to every assignment.</p><p>With native Norwegian, near-native Danish and fluent English, I focus on what readers actually need to understand. That means keeping technical terminology precise, instructions unambiguous and communication natural, without losing the meaning of the source.</p><p>There is no unnecessary handoff. You brief me directly, I flag uncertainties early and I deliver against your agreed requirements. From reference materials and terminology to final checks, I treat quality as a process, not a last-minute step.</p><div className="workflow-tools"><strong>Tools I work with</strong><p>Trados Studio · memoQ · Phrase · XTM Cloud · Smartcat · Xbench</p></div><div className="profile-download"><a className="primary-link" href="/downloads/precious-afolabi-profile.pdf" download>Download my professional profile</a><span>One page · PDF · Language pairs, services and workflow</span></div><div className="about-links"><a href="/about">Read my story ↗</a><a href="https://www.linkedin.com/in/precious-afolabi-989084284/" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href="https://www.proz.com/translator/4615033" target="_blank" rel="noopener noreferrer">ProZ profile</a></div></div></section>
      <section className="workflow-section shell section" aria-labelledby="workflow-title"><div className="section-head"><p className="eyebrow">HOW I WORK</p><h2 id="workflow-title">Clarity at every step.<br/><em>Confidence at handover.</em></h2><p>A dependable process keeps communication simple and your project on track.</p></div><div className="workflow-grid"><article><span>01</span><h3>Scope it right</h3><p>We establish the audience, language direction, deliverables, references and timing upfront. You know exactly what I’ll handle.</p></article><article><span>02</span><h3>Translate with intent</h3><p>I work with your terminology and tools, resolve context where possible and raise targeted questions rather than making risky assumptions.</p></article><article><span>03</span><h3>Review before release</h3><p>I review accuracy, consistency, numbers, tags and formatting before handing over files that match the agreed specification.</p></article></div></section>
      <section className="project-questions shell" aria-labelledby="questions-title"><div><p className="eyebrow">BEFORE WE BEGIN</p><h2 id="questions-title">Before we begin,<br/><em>the essentials.</em></h2></div><div className="question-list"><details><summary>Which language pairs do you work with?</summary><p>I work across English and Norwegian, English and Danish, and Norwegian and Danish in both directions. Share the audience, language variant and service you need in your enquiry.</p></details><details><summary>What do you need to prepare a quote?</summary><p>Send the language pair, content type, service, approximate word count and deadline with its time zone. Source files and reference material help me confirm the scope and delivery format.</p></details><details><summary>How are rates and delivery dates agreed?</summary><p>I quote after reviewing the language pair, service, content complexity, volume, file format and deadline. Share your files and time zone so I can confirm availability and the scope before work begins.</p></details><details><summary>Which files and references should I send?</summary><p>Email the source files with any glossary, style guide, previous translations and instructions about the final format. For software, screenshots or string context help. For audio and video, include the duration and the transcript or subtitle format you need.</p></details><details><summary>Can you work in my CAT tool?</summary><p>I work with Trados Studio, memoQ, Phrase, XTM Cloud and Smartcat, and use Xbench for linguistic quality checks. Share your platform and workflow requirements before we start.</p></details><details><summary>Do you handle ongoing localization work?</summary><p>Yes. I support individual assignments and recurring translation, revision, MTPE and QA workflows. Availability and delivery schedules are agreed around your scope.</p></details></div></section>
      <section id="contact" className="contact-section"><div className="shell contact-wrap"><div className="contact-copy"><p className="eyebrow">LET’S TALK</p><h2>Have something<br/><em>worth saying?</em></h2><p>Tell me what you’re creating, who needs to understand it and when it needs to be ready. I’ll review your brief personally and respond with a clear way forward.</p><a className="email-link" href={`mailto:${email}`}>{email}</a><div className="contact-links"><a href="https://wa.me/447479414190" target="_blank" rel="noopener noreferrer">WhatsApp</a><a href="https://www.linkedin.com/in/precious-afolabi-989084284/" target="_blank" rel="noopener noreferrer">LinkedIn</a></div></div><form className="contact-form" action={formspreeEndpoint} method="POST" onSubmit={submitEnquiry} aria-busy={formState === "sending"}><h3>Tell me about your project</h3><div className="form-row"><label>Name<input name="name" autoComplete="name" required maxLength={120}/></label><label>Work email<input name="email" type="email" autoComplete="email" required maxLength={180}/></label></div><div className="form-row"><label>Language pair<select name="Language pair" required defaultValue=""><option value="" disabled>Select a language pair</option>{["English to Norwegian","Norwegian to English","English to Danish","Danish to English","Norwegian to Danish","Danish to Norwegian"].map(pair => <option key={pair}>{pair}</option>)}</select></label><label>Deadline<input name="Deadline" placeholder="Date and time zone" maxLength={100}/></label></div><div className="form-row"><label>Service<select name="service" required ref={serviceSelect} defaultValue=""><option value="" disabled>Select a service</option>{services.map(([title]) => <option key={title} value={title}>{title}</option>)}<option value="Multiple services / advice">Multiple services / advice</option></select></label><label>Approximate scope<input name="scope" placeholder="e.g. 2,000 words or 20 screens" maxLength={120}/></label></div><label>Tell me about the work<textarea name="message" rows={5} required maxLength={4000} placeholder="Audience, content type, file format and any key requirements"/></label><input type="text" name="_gotcha" className="honeypot" tabIndex={-1} autoComplete="off" aria-hidden="true"/><button className="submit-button" type="submit" disabled={formState === "sending"}>{formState === "sending" ? "Sending…" : "Send enquiry"}</button><p className="form-note">Formspree processes your enquiry and forwards it to my email. I use your contact details to respond to your project request. Read the <a href="/privacy">privacy notice</a>. <a href={`mailto:${email}?subject=Project%20files`}>Send project files by email</a>.</p>{formState === "sent" && <p className="form-feedback" role="status">Your enquiry was sent. I’ll reply by email.</p>}{formState === "error" && <p className="form-feedback error" role="alert">{formError} Email me directly at <a href={`mailto:${email}`}>{email}</a>.</p>}</form></div></section>
    </main><LuxuryFooter />
  </>;
}
