export const serviceCatalog = [
  {slug:'translation',title:'Translation',summary:'Norwegian, Danish and English translation for documents where meaning, terminology and tone matter.',intro:'Clear, accurate language for the people who need to read, use and trust your content.',content:['Technical manuals and engineering documentation','Medical device instructions and supporting documents','Legal, business and marketing content'],checks:['Source meaning and completeness','Approved terminology and reference material','Numbers, units, names and formatting'],deliverable:'Translated content in the agreed format, with queries or delivery notes where a source needs clarification.'},
  {slug:'localization',title:'Localization',summary:'Software, websites, games and campaigns adapted for Norwegian and Danish readers.',intro:'Language that fits the product, the audience and the place it appears.',content:['Software interfaces, menus and onboarding','Game dialogue, tutorials and player facing content','Websites, ecommerce and marketing campaigns'],checks:['Tone, audience and cultural context','UI constraints, tags and placeholders','Consistency across screens and content types'],deliverable:'Localized strings or content in your chosen workflow, with notes on contextual decisions where needed.'},
  {slug:'revision',title:'Revision',summary:'A careful comparison of a translation with its source to resolve errors and improve clarity.',intro:'A fresh linguistic review before your content reaches its readers.',content:['Translations prepared by another linguist','Updated document versions','Technical, medical and digital content'],checks:['Accuracy, omissions and additions','Terminology, grammar and natural phrasing','Alignment with your brief and style guide'],deliverable:'Revised content with tracked changes or review comments when required by your workflow.'},
  {slug:'mtpe',title:'MTPE',summary:'Machine translation post editing against the source, with the quality level agreed in advance.',intro:'A source checked edit that brings machine translated content into line with your requirements.',content:['Equipment and technical documentation','Medical and product documentation','Software and recurring content workflows'],checks:['Mistranslations and missing meaning','Terminology and fluent target language','Numbers, tags, units and repeated strings'],deliverable:'Post edited content to the agreed level, using your CAT tool, terminology and delivery instructions.'},
  {slug:'lqa',title:'Linguistic QA',summary:'Review of language in context, with findings your product team can act on.',intro:'Check what the words mean where your users actually encounter them.',content:['Software interfaces and websites','Game content and multilingual product testing','Screenshots, builds and final content'],checks:['Context, user actions and permissions','Consistency, truncation and placeholders','Clear issue descriptions and corrections'],deliverable:'Reviewed content and actionable linguistic findings in your reporting format, with corrections or recommendations.'},
  {slug:'subtitling',title:'Subtitling',summary:'Subtitle translation and review that account for dialogue, timing and reading flow.',intro:'Natural language that works within the rhythm and space of the screen.',content:['Dialogue and narrative content','Product and training videos','Marketing and audiovisual material'],checks:['Meaning, tone and terminology','Reading flow and agreed length limits','Timing and subtitle file requirements'],deliverable:'Subtitle content in the agreed file format and specification. Share your timing requirements and available source files in the brief.'},
  {slug:'transcription',title:'Transcription',summary:'Norwegian and Danish speech captured with attention to names, terminology and your required format.',intro:'A dependable written record for your next stage of work.',content:['Interviews and recorded conversations','Training, research and business recordings','Audio and video content'],checks:['Names and specialist terminology','Speaker labels and requested timestamps','Agreed verbatim or edited style'],deliverable:'A transcript in the agreed format, with timestamps and speaker identification where requested.'},
  {slug:'dtp',title:'DTP & layout review',summary:'Language aware checks of final files, including text fit, tables and page flow.',intro:'Make sure the translated document works on the page as well as in the text.',content:['Technical and medical documentation','Multilingual documents and presentations','Final layouts ready for handover'],checks:['Text overflow and missing content','Headings, numbering and tables','Page flow and language consistency'],deliverable:'Layout reviewed files or clearly marked corrections. The editing scope depends on your source files and is agreed before work starts.'},
];
